// Player panel actionType
export const TOGGLE_PLAYER = 'TOGGLE_PLAYER';
export const CHANGE_PLAYER_MODE = 'CHANGE_PLAYER_MODE';
export const FETCH_SONGURL_BEGIN = 'FETCH_SONGURL_BEGIN';
export const FETCH_SONGURL_SUCCESS = 'FETCH_SONGURL_SUCCESS';
export const FETCH_SONGURL_FAILURE = 'FETCH_SONGURL_FAILURE';
export const PLAY_NEXT_SONG = 'PLAY_NEXT_SONG';
export const PLAY_PREVIOUS_SONG = 'PLAY_NEXT_SONG';

// SongList
export const REQUEST_SONGLIST = 'REQUEST_SONGLIST';
export const RECEIVE_SONGLIST = 'RECEIVE_SONGLIST';

// Recommend
export const REQUEST_RECOMMEND_LIST = 'REQUEST_RECOMMEND_LIST';
export const RECEIVE_RECOMMEND_LIST = 'RECEIVE_RECOMMEND_LIST';

// Found
export const FETCHING_FOUND_LIST = 'FETCHING_FOUND_LIST';
export const FETCH_FOUND_LIST_SUCCESS = 'FETCH_FOUND_LIST_SUCCESS';
export const FETCH_FOUND_LIST_FAILURE = 'FETCH_FOUND_LIST_FAILURE';
