// Player panel actionType
export const TOGGLE_PLAYER = "TOGGLE_PLAYER";
export const CHANGE_PLAYER_MODE= "CHANGE_PLAYER_MODE";
export const FETCH_SONGURL_BEGIN   = 'FETCH_SONGURL_BEGIN';
export const FETCH_SONGURL_SUCCESS = 'FETCH_SONGURL_SUCCESS';
export const FETCH_SONGURL_FAILURE = 'FETCH_SONGURL_FAILURE';
export const PLAY_NEXT_SONG= "PLAY_NEXT_SONG";
export const PLAY_PREVIOUS_SONG= "PLAY_NEXT_SONG";
